restTemplate:
  factory:
    readTimeout: 10000
    connectTimeout: 5000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5

app:
  name: enclave-api
  henesis-wallet:
    url: http://localhost:3000
    api-secret: XP0SZ8TY/6O6hlMAfjcAtmESj/ihFlVed/nkNTDHrmo=
    access-token: eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImptZWVmMDgwMkBnbWFpbC5jb20iLCJpZCI6IjI2ZTQyMjliOTQ0ZWZlNjNiYWU4MThlZDMyYTY0YTkxIiwidHlwZSI6IkxPTkciLCJsb25nVHlwZSI6dHJ1ZSwiaXNzIjoiaGVuZXNpcy13YWxsZXQtaWRlbnRpdHktcHJvZC10ZXN0bmV0IiwiaWF0IjoxNjA1NjY4Mzg5LCJleHAiOjE5MjEwMjgzODl9.6d1HBljaYYaDB0xkI8zZ7wiUcGrDgx7K-PcfGUE1JPwOuZnng7QQWcvHrLM98C6-m8PENLNKr7m8-N7uIriqAw

    eth-masterWalletId: fa869ba8733854ea3401eb4f1aac7c66
    eth-passphrase: ethPassphrase
    eth-size: 500

    btc-walletId: 22b0611bfd5a98441dbdd51a1c9d8e24
    btc-passphrase: btcPassphrase
    btc-size: 500

    klay-masterWalletId: ec198a2a5c901dfb8c2e8124a78a2e7a
    klay-passphrase: klayPassphrase
    klay-size: 500


spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/henesis
    username: user
    password: password
    platform: postgres
    hikari:
      auto-commit: false
      idle-timeout: 10000
      minimumIdle: 10
      maximum-pool-size: 30
      read-only: false
      connection-timeout: 20000
      data-source-properties:
        stringtype: unspecified
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false