app:
  name: enclave-api
  henesis:
    url: http://localhost:3000
    api-secret: pvZ4CrBm5z9/uBSQgmkOvm/kDxkFiLxx8RSZZMkWRo4=
    access-token: eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6InRvYnlAaGFlY2hpLmlvIiwiaWQiOiJjMDBiNWIxMDA4NjU4MGM2ZTc0NTZlZDQwYTcxMDkzZSIsInR5cGUiOiJMT05HIiwiaXNzIjoid2FsbGV0LXByb2QtdGVzdG5ldCIsImlhdCI6MTU5NDcyNzM2MCwiZXhwIjoxMDAwMDAxNTk0NzI3MzYwfQ.ueBjMrq3xT9F86geXxaoaIxQyXjKG4coMweSHj4muJw6yojjtbfuhUKfIjGFUE1kFDrmR-sT_G7uEOU4WKUMCA

    eth-master-wallet-id: "3d5898988fdcbb77535eb7eade178a8e"
    eth-master-wallet-address: "0x2eda67cc0aaf88a7defc80c51e5d0e543852de0f"
    eth-passphrase: "password"
    eth-polling-size: 500
    eth-polling-interval: 10000 # 10 seconds

    klay-master-wallet-id: "d7d1a1d9a9c526c9c6f75bc0a58055e1"
    klay-master-wallet-address: "0x7d59b57eb8913bf0bd59f08f83fd5676aeb5482c"
    klay-passphrase: "password"
    klay-polling-size: 500
    klay-polling-interval: 3000 # 3 seconds

    btc-master-wallet-id: "d74a91146d1d36d518e461e469c8c911"
    btc-master-wallet-address: "2N6jSUMrrHbdVTMmX61avsuG6ou7VH4y5zs"
    btc-passphrase: "password"
    btc-polling-size: 500
    btc-polling-interval: 180000 # 3 minute

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/henesis
    username: user
    password: password
    platform: postgres
    hikari:
      auto-commit: false
      idle-timeout: 10000
      minimumIdle: 10
      maximum-pool-size: 30
      read-only: false
      connection-timeout: 20000
      data-source-properties:
        stringtype: unspecified
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false